### PR TITLE
New default apps and clearer english

### PR DESCRIPTION
**Pull request by tecdude**
I added three default apps and cleaned the English in the setup logs

### CODE REVIEW

**Comment by tecdude** [comment]
Tidied up the language, fixed grammar, made the language more concise

**Review by grzegorz914 — CHANGES_REQUESTED** [review]
This inputs can not be added as default because are available if you use “Load Inputs From Device”. I this case we have duplicate inputs on the list. Other changes can be merged after change this PR.

**Comment by tecdude** [comment]
I have removed the default apps that I added

**Review by grzegorz914 — CHANGES_REQUESTED** [review]
The authorization manager is not more in test phase. It is working correct now.

**Pull request merged**
